from models.__init__ import CONN, CURSOR
from models.team import Team

def seed_database():
    Team.create_table()
    Team.drop_table()
    
atlanta_hawks = Team("Atlanta Hawks", "Southeast")
boston_celtics = Team("Boston Celtics", "Atlantic")
brooklyn_nets = Team("Brooklyn Nets", "Atlantic")
charlotte_hornets = Team("Charlotte Hornets", "Southeast")
chicago_bulls = Team("Chicago Bulls", "Central")
cleveland_cavaliers = Team("Cleveland Cavaliers", "Central")
dallas_mavericks = Team("Dallas Mavericks", "Southwest")
denver_nuggets = Team("Denver Nuggets", "Northwest")
detroit_pistons = Team("Detroit Pistons", "Central")
golden_state_warriors = Team("Golden State Warriors", "Pacific")
houston_rockets = Team("Houston Rockets", "Southwest")
indiana_pacers = Team("Indiana Pacers", "Central")
la_clippers = Team("LA Clippers", "Pacific")
los_angeles_lakers = Team("Los Angeles Lakers", "Pacific")
memphis_grizzlies = Team("Memphis Grizzlies", "Southwest")
miami_heat = Team("Miami Heat", "Southeast")
milwaukee_bucks = Team("Milwaukee Bucks", "Central")
minnesota_timberwolves = Team("Minnesota Timberwolves", "Northwest")
new_orleans_pelicans = Team("New Orleans Pelicans", "Southwest")
new_york_knicks = Team("New York Knicks", "Atlantic")
oklahoma_city_thunder = Team("Oklahoma City Thunder", "Northwest")
orlando_magic = Team("Orlando Magic", "Southeast")
philadelphia_76ers = Team("Philadelphia 76ers", "Atlantic")
phoenix_suns = Team("Phoenix Suns", "Pacific")
portland_trail_blazers = Team("Portland Trail Blazers", "Northwest")
sacramento_kings = Team("Sacramento Kings", "Pacific")
san_antonio_spurs = Team("San Antonio Spurs", "Southwest")
toronto_raptors = Team("Toronto Raptors", "Atlantic")
utah_jazz = Team("Utah Jazz", "Northwest")
washington_wizards = Team("Washington Wizards", "Southeast")

seed_database()
print("Seeded database")