from models.__init__ import CONN, CURSOR
from models.driver import Driver
from models.brand import Brand

def seed_database():
    Brand.drop_table()
    Brand.create_table()
    Driver.drop_table()
    Driver.create_table()

    Lamborghini = Brand.create("Lamborghini", "Italy")
    Ferrari = Brand.create("Ferrari", "Italy")
    MercedesBenz = Brand.create("Mercedes-Benz", "Germany")
    Porsche = Brand.create("Porsche", "Germany")
    Audi = Brand.create("Audi", "Germany")
    Toyota = Brand.create("Toyota", "Japan")
    Honda = Brand.create("Honda", "Japan")
    Nissan = Brand.create("Nissan", "Japan")
    Mitsubishi = Brand.create("Mitsubishi", "Japan")
    Subaru = Brand.create("Subaru", "Japan")
    Lexus = Brand.create("Lexus", "Japan")
    Acura = Brand.create("Acura", "Japan")
    Kia = Brand.create("Kia", "South Korea")
    Hyundai = Brand.create("Hyundai", "South Korea")
    Genesis = Brand.create("Genesis", "South Korea")
    Chevrolet = Brand.create("Chevrolet", "United States")
    Ford = Brand.create("Ford", "United States")
    Chrysler = Brand.create("Chrysler", "United States")
    Dodge = Brand.create("Dodge", "United States")
    Jeep = Brand.create("Jeep", "United States")
    Buick = Brand.create("Buick", "United States")
    Cadillac = Brand.create("Cadillac", "United States")
    GMC = Brand.create("GMC", "United States")
    Ram = Brand.create("Ram", "United States")
    AstonMartin = Brand.create("Aston Martin", "United Kingdom")
    Jaguar = Brand.create("Jaguar", "United Kingdom")
    LandRover = Brand.create("Land Rover", "United Kingdom")
    Mini = Brand.create("Mini", "United Kingdom")
    Volvo = Brand.create("Volvo", "Sweden")
    Saab = Brand.create("Saab", "Sweden")
    Skoda = Brand.create("Skoda", "Czech Republic")
    VolksWagen = Brand.create("Volkswagen", "Germany")
    Peugeot = Brand.create("Peugeot", "France")
    Citroen = Brand.create("Citroen", "France")
    Renault = Brand.create("Renault", "France")
    Fiat = Brand.create("Fiat", "Italy")
    AlfaRomeo = Brand.create("Alfa Romeo", "Italy")
    Lancia = Brand.create("Lancia", "Italy")
    Maserati = Brand.create("Maserati", "Italy")
    Bugatti = Brand.create("Bugatti", "France")
    McLaren = Brand.create("McLaren", "United Kingdom")
    Lotus = Brand.create("Lotus", "United Kingdom")
    TVR = Brand.create("TVR", "United Kingdom")
    RollsRoyce = Brand.create("Rolls-Royce", "United Kingdom")
    Bentley = Brand.create("Bentley", "United Kingdom")
    Morgan = Brand.create("Morgan", "United Kingdom")
    Koenigsegg = Brand.create("Koenigsegg", "Sweden")
    Pagani = Brand.create("Pagani", "Italy")
    Fisker = Brand.create("Fisker", "United States")
    Lucid = Brand.create("Lucid", "United States")
    Rivian = Brand.create("Rivian", "United States")
    Karma = Brand.create("Karma", "United States")
    Tesla = Brand.create("Tesla", "United States")
    Lucid = Brand.create("Lucid", "United States")
    Nikola = Brand.create("Nikola", "United States")
    Byton = Brand.create("Byton", "China")
    Xpeng = Brand.create("Xpeng", "China")
    Nio = Brand.create("Nio", "China")
    SAIC = Brand.create("SAIC", "China")
    BYD = Brand.create("BYD", "China")
    Geely = Brand.create("Geely", "China")
    Proton = Brand.create("Proton", "Malaysia")
    Perodua = Brand.create("Perodua", "Malaysia")
    Tata = Brand.create("Tata", "India")
    Mahindra = Brand.create("Mahindra", "India")
    Maruti_Suzuki = Brand.create("Maruti Suzuki", "India")
    Mahindra = Brand.create("Mahindra", "India")
    SsangYong = Brand.create("SsangYong", "South Korea")
    Genesis = Brand.create("Genesis", "South Korea")
    Isuzu = Brand.create("Isuzu", "Japan")
    Hino = Brand.create("Hino", "Japan")
    Scion = Brand.create("Scion", "United States")
    Hummer = Brand.create("Hummer", "United States")
    DeLorean = Brand.create("DeLorean", "United States")
    Studebaker = Brand.create("Studebaker", "United States")
    AMC = Brand.create("AMC", "United States")

    Ehad = Driver.create("Ehad", 22)
    Johnson = Driver.create("Johnson", 22)

seed_database()
print("Seeded database")
